auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: EricLiu.com
url: http://eric00liu.github.io
feed: /atom.xml
author_info: <a href="http://eric00liu.github.io/">EricLiu</a>
